variables:
  DEBIAN_FRONTEND: noninteractive
  GIT_DEPTH: 0
  GIT_STRATEGY: none
  GIT_SUBMODULE_STRATEGY: none
  BRANCH_MAIN: master
  BRANCH_WORK: develop

stages:
- build
- deploy

build_pydtnn:
  variables:
    GIT_STRATEGY: fetch
    GIT_SUBMODULE_STRATEGY: recursive
    PIP_ROOT_USER_ACTION: ignore
    PIP_DISABLE_PIP_VERSION_CHECK: "1"
    PIP_CACHE_DIR: $CI_PROJECT_DIR/build/pip

  stage: build
  timeout: 5h
  rules:
  - if: $CI_COMMIT_BRANCH == $BRANCH_WORK

  tags: [ lorca-ubuntu ]
  image: python:latest

  cache:
  - paths:
    - build
    when: always

  before_script:
  - make sync
  - apt-get update
  - mkdir -p ./build
  - export $(make env | xargs)
  - make deps APT="apt-get -o dir::cache::archives=${PWD:?}/build/apt"
  script:
  - make pydtnn-clean
  - make build NPROC=1
  - make install PYDTNN_PKG=test,lint
  - make test NPROC=1
  - make lint NPROC=1

  artifacts:
    reports:
      junit: ./build/pydtnn/tests.xml
      coverage_report:
        coverage_format: cobertura
        path: ./build/pydtnn/coverage.xml
      codequality: ./build/pydtnn/lint.json
    paths:
    - ./build/pydtnn/*
    expire_in: 1d
    when: always
  coverage: '/TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'

deploy_git:
  variables:
    GIT_STRATEGY: fetch

  stage: deploy
  timeout: 5m
  rules:
  - if: $CI_COMMIT_BRANCH == $BRANCH_WORK

  image: registry.gitlab.com/gitlab-org/cli:latest
  tags: [ lorca-ubuntu ]

  needs:
  - job: build_pydtnn
    artifacts: true

  rules:
  - if: $CI_COMMIT_BRANCH == $BRANCH_WORK

  before_script:
  - GIT_REMOTE_NAME=$(git remote)
  - GIT_REMOTE_URL=$(git remote get-url "${GIT_REMOTE_NAME:?}")
  - GIT_TAG=$(basename ./build/pydtnn/pydtnn-*.tar.gz | sed -nE 's|^pydtnn-(.*)\.tar\.gz$|v\1|p')
  - git remote set-url "${GIT_REMOTE_NAME}" "${GIT_REMOTE_URL/gitlab-ci-token:[^@]*@/gitlab-ci-token:${GITLAB_TOKEN:?}@}"
  - glab auth login --hostname "${CI_SERVER_FQDN:?}" --token "${GITLAB_TOKEN:?}"
  script:
  - git fetch "${GIT_REMOTE_NAME:?}" "${BRANCH_MAIN:?}"
  - git checkout -B "${BRANCH_MAIN:?}" "${GIT_REMOTE_NAME:?}/${BRANCH_MAIN:?}"
  - git merge "${CI_COMMIT_SHA:?}" --ff-only
  - git tag "${GIT_TAG:?}" "${CI_COMMIT_SHA:?}" || true
  - git push "${GIT_REMOTE_NAME:?}" "${BRANCH_MAIN:?}" "${GIT_TAG:?}"

deploy_gitlab:
  variables:
    GIT_STRATEGY: fetch

  stage: deploy
  timeout: 5m
  rules:
  - if: $CI_COMMIT_BRANCH == $BRANCH_WORK

  tags: [ lorca-ubuntu ]
  image: registry.gitlab.com/gitlab-org/cli:latest

  needs:
  - job: build_pydtnn
    artifacts: true

  before_script:
  - RELEASE_TAG=continuous
  - GIT_TAG=$(basename ./build/pydtnn/pydtnn-*.tar.gz | sed -nE 's|^pydtnn-(.*)\.tar\.gz$|v\1|p')
  - glab auth login --hostname "${CI_SERVER_FQDN:?}" --token "${GITLAB_TOKEN:?}"
  script:
  - glab release delete "${RELEASE_TAG:?}" -ty || true
  - glab release create "${RELEASE_TAG:?}" ./build/pydtnn/* --ref "${CI_COMMIT_SHA:?}" --name 'Continuous build'

deploy_pypi:
  variables:
    GIT_STRATEGY: fetch
    PIP_ROOT_USER_ACTION: ignore
    PIP_DISABLE_PIP_VERSION_CHECK: "1"
    PIP_CACHE_DIR: $CI_PROJECT_DIR/build/pip
    TWINE_NON_INTERACTIVE: "1"

  stage: deploy
  timeout: 5m
  rules:
  - if: $CI_COMMIT_BRANCH == $BRANCH_WORK

  tags: [ lorca-ubuntu ]
  image: python:latest

  needs:
  - job: build_pydtnn
    artifacts: true

  before_script:
  - GIT_TAG=$(basename ./build/pydtnn/pydtnn-*.tar.gz | sed -nE 's|^pydtnn-(.*)\.tar\.gz$|v\1|p')
  - GIT_COMMIT=$(git rev-list -n1 "${GIT_TAG:?}")
  - '[ "${GIT_COMMIT:?}" = "${CI_COMMIT_SHA:?}" ] || exit 0'
  - apt-get update
  - make pydtnn-deps APT="apt-get -o dir::cache::archives=${PWD:?}/build/apt"
  script:
  - twine upload -u '__token__' -p "${PYPI_TOKEN:?}" ./build/pydtnn/pydtnn-*