stages:
  - build
  #- release

variables:
  PIP_DISABLE_PIP_VERSION_CHECK: "1"

job_build:
  stage: build

  tags: [ lorca-ubuntu ]
  image: python:3.13

  services:
    - name: docker:dind
      command: ["--tls=false"]
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    CI_DEBUG_SERVICES: "true"

  before_script:
    - apt-get update
    - apt-get install -y docker.io netcat-openbsd
    #- pip install build cibuildwheel
  script:
  - echo "Runner: $CI_RUNNER_DESCRIPTION"
  - echo "Executor: $CI_RUNNER_EXECUTABLE_ARCH"
  - docker info || true
  - ps aux || true
  - ip addr || true
  - env | sort
  - cat /proc/1/cgroup || true
  - mount || true
  - ls -la /var/run || true
  - getent hosts docker || true
  - nc -zv docker 2375 || true
    #- python -m build --sdist --outdir ./build/
    #- python -m cibuildwheel --output-dir ./build/

  #artifacts:
  #  paths:
  #    - ./build/

#job_release:
#  stage: release
#
#  tags: [ lorca-ubuntu ]
#  image: registry.gitlab.com/gitlab-org/cli:latest
#
#  needs:
#    - job: job_build
#      artifacts: true
#
#  script:
#    - glab auth login --hostname lorca.act.uji.es/gitlab --token "$GLAB_TOKEN"
#    - glab release create "ci-$CI_COMMIT_SHA" --ref "$CI_COMMIT_SHA"