stages:
- make
- merge
- push

variables:
  BRANCH_MAIN: main
  BRANCH_WORK: develop
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: none

job_make:
  stage: make

  variables:
    PYTHON_VERSION: latest
    PIP_DISABLE_PIP_VERSION_CHECK: "1"
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/build/pip"

  rules:
  - if: '$CI_COMMIT_BRANCH == $BRANCH_WORK'

  tags: [ lorca-ubuntu ]
  image: python:$PYTHON_VERSION

  cache:
  - key:
      files:
      - Makefile
      - pyproject.toml
    paths:
    - build
    - /var/cache/apt/archives
    when: always

  before_script:
  - apt-get update
  - mkdir -p ./build
  - export $(make env | xargs)
  - make pydtnn-deps  # vendor-deps
  # - make vendor-install PROCS=1
  script:
  - make pydtnn-clean
  - make pydtnn-build PROCS=1
  - WHEEL=$(echo ./build/pydtnn/*.whl)
  - pip install ${WHEEL:?}[build,test,quality]
  - TAG=v$(python -c "from importlib.metadata import version; print(version('pydtnn'))")
  - printf '%s\n' GIT_TAG=${TAG:?} PUBLIC_TAG=$(git tag | grep -xF ${TAG:?}) > ./build/env
  - make pydtnn-check PROCS=1

  coverage: '/TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'

  artifacts:
    reports:
      dotenv: ./build/env
      junit: ./build/tests
      coverage_report:
        coverage_format: cobertura
        path: ./build/coverage
      codequality: ./build/quality
    paths:
    - ./build/pydtnn/
    # - ./build/vendor.log
    expire_in: 1d
    when: always

# job_merge:
#   stage: merge
# 
#   rules:
#   - if: '$CI_COMMIT_BRANCH == $BRANCH_WORK'
# 
#   image: registry.gitlab.com/gitlab-org/cli:latest
#   tags: [ lorca-ubuntu ]
# 
#   needs:
#   - job: job_test
# 
#   rules:
#   - if: '$CI_COMMIT_BRANCH == $BRANCH_WORK'
# 
#   resource_group: merge
# 
#   before_script:
#   - glab auth login --hostname lorca.act.uji.es/gitlab --token "${CI_JOB_TOKEN:?}"
#   - git config --global user.email "ci@lorca.act.uji.es"
#   - git config --global user.name "GitLab CI"
#   script:
#   - git checkout ${$BRANCH_MAIN:?}
#   - git merge origin/${BRANCH_WORK:?} --ff-only
#   - git push origin ${$BRANCH_MAIN:?}

job_push:
  stage: push

  rules:
  - if: '$CI_COMMIT_BRANCH == $BRANCH_WORK && $PUBLIC_TAG == ""'

  tags: [ lorca-ubuntu ]
  image: registry.gitlab.com/gitlab-org/cli:latest

  needs:
  - job: job_make
    artifacts: true

  before_script:
  - glab auth login --hostname lorca.act.uji.es/gitlab --token "${CI_JOB_TOKEN:?}"
  script:
  - glab release delete "${GIT_TAG:?}" --yes || true
  - glab release create "${GIT_TAG:?}" ./build/pydtnn/* --ref "${CI_COMMIT_SHA:?}" --name "PyDTNN ${GIT_TAG:?}"