"""Python interface to the NVIDIA NCCL library"""

import ctypes
import ctypes.util
import logging
import sys
from enum import Enum

__all__ = (
    "DataType",
    "NcclComm",
    "NcclError",
    "NcclUniqueId",
    "RedOp",
    "ncclAllGather",
    "ncclAllReduce",
    "ncclBroadcast",
    "ncclCheckStatus",
    "ncclCommAbort",
    "ncclCommCount",
    "ncclCommCuDevice",
    "ncclCommDestroy",
    "ncclCommGetAsyncError",
    "ncclCommInitAll",
    "ncclCommInitRank",
    "ncclCommUserRank",
    "ncclGetUniqueId",
    "ncclGetVersion",
    "ncclGroupEnd",
    "ncclGroupStart",
    "ncclRecv",
    "ncclReduce",
    "ncclReduceScatter",
    "ncclSend",
)

logger = logging.getLogger(__name__)


if sys.platform in ("linux2", "linux"):
    _libnccl_libname_list = ["libnccl.so"]
elif sys.platform == "darwin":
    _libnccl_libname_list = ["libnccl.dylib"]
elif sys.platform == "win32":
    _libnccl_libname_list = ["libnccl.dll"]
else:
    raise NotImplementedError("PyDTNN NCCL: current platform is not yet supported!")

_libnccl = None
for _libnccl_libname in _libnccl_libname_list:
    try:
        _libnccl = ctypes.cdll.LoadLibrary(_libnccl_libname)
    except OSError:
        pass
    else:
        break
if _libnccl is None:
    raise OSError("NCCL library not found")

# NCCL error
_libnccl.ncclGetErrorString.restype = ctypes.c_char_p
_libnccl.ncclGetErrorString.argtypes = [ctypes.c_int]


class NcclError(Exception):
    """Custom exception for NCCL errors."""

    def __init__(self, status: int) -> None:
        """Initializes NcclError with the NCCL status code.

        Parameters
        ----------
        status : int
            The NCCL error code.
        """
        self.status = status

    def __str__(self) -> str:
        """Returns a human-readable string representation of the NCCL error."""
        assert _libnccl
        error = _libnccl.ncclGetErrorString(self.status)
        return f"{error.decode('utf-8')}"


def ncclCheckStatus(status: int) -> None:
    """Raise NCCL exception if the status code indicates an error.

    Parameters
    ----------
    status : int
        NCCL error code.
    """

    if status != 0:
        raise NcclError(status)


NCCL_UNIQUE_ID_BYTES = 128


class NcclUniqueId(ctypes.Structure):
    """Represents a unique identifier for NCCL communicators."""

    _fields_ = [("internal", ctypes.c_char * NCCL_UNIQUE_ID_BYTES)]


class NcclComm(ctypes.Structure):
    """Represents an NCCL communicator."""


ncclComm_t = ctypes.POINTER(NcclComm)

# Helper functions

# Return the NCCL_VERSION_CODE of the NCCL library in the supplied integer.
# This integer is coded with the MAJOR, MINOR and PATCH level of the
# NCCL library

# ncclResult_t  ncclGetVersion(int *version);
_libnccl.ncclGetVersion.restype = ctypes.c_size_t
_libnccl.ncclGetVersion.argtypes = []


def ncclGetVersion() -> int:
    """Get the NCCL library version.

    The version is returned as an integer where bits represent major, minor, and patch versions.

    Returns
    -------
    int
        The NCCL version code.
    """
    version = ctypes.c_int()
    assert _libnccl
    _libnccl.ncclGetVersion(ctypes.byref(version))
    return version.value


# ncclResult_t  ncclGetUniqueId(NcclUniqueId* uniqueId);
_libnccl.ncclGetUniqueId.restype = int
_libnccl.ncclGetUniqueId.argtypes = []


def ncclGetUniqueId() -> NcclUniqueId:
    """Generates a unique ID to be used in `ncclCommInitRank`.

    This function should be called once, and the generated ID must be distributed
    to all ranks in the communicator before calling `ncclCommInitRank`.

    Returns
    -------
    NcclUniqueId
        The generated unique ID.
    """

    unique_id = NcclUniqueId()
    assert _libnccl
    status = _libnccl.ncclGetUniqueId(ctypes.byref(unique_id))
    ncclCheckStatus(status)
    return unique_id


# ncclResult_t  ncclCommInitRank(ncclComm_t* comm, int nranks, NcclUniqueId comm_id, int rank);
_libnccl.ncclCommInitRank.restype = int
_libnccl.ncclCommInitRank.argtypes = [
    ctypes.POINTER(ncclComm_t),
    ctypes.c_int,
    NcclUniqueId,
    ctypes.c_int,
]


def ncclCommInitRank(nranks: int, comm_id: NcclUniqueId, rank: int) -> ctypes._Pointer[NcclComm]:
    """Creates a new NCCL communicator for a given rank.

    This is the multi-thread/process version of communicator initialization.
    The `rank` must be between 0 and `nranks`-1 and unique within a communicator clique.
    Each rank is associated with a CUDA device, which must be set before calling
    this function. `ncclCommInitRank` implicitly synchronizes with other ranks,
    so it must be called by different threads/processes or within a `ncclGroupStart`/`ncclGroupEnd` block.

    Parameters
    ----------
    nranks : int
        The total number of ranks in the communicator.
    comm_id : NcclUniqueId
        The unique ID generated by `ncclGetUniqueId`.
    rank : int
        The rank of the current process/thread.

    Returns
    -------
    ncclComm_t
        The initialized NCCL communicator.
    """

    comm = ncclComm_t()
    assert _libnccl
    status = _libnccl.ncclCommInitRank(ctypes.byref(comm), nranks, comm_id, rank)
    ncclCheckStatus(status)
    return comm


# ncclResult_t  ncclCommInitAll(ncclComm_t* comm, int ndev, const int* dev_list);
_libnccl.ncclCommInitAll.restype = int
_libnccl.ncclCommInitAll.argtypes = [ctypes.c_void_p, ctypes.c_int, ctypes.POINTER(ctypes.c_int)]


def ncclCommInitAll(dev_list: tuple[int, ...] | None) -> ctypes._Pointer[NcclComm]:
    """Creates a clique of communicators for a single process.

    This is a convenience function to create a single-process communicator clique.
    It returns an array of `ndev` newly initialized communicators.
    `comm` should be pre-allocated with size at least `ndev` * `sizeof(ncclComm_t)`.
    If `dev_list` is NULL, the first `ndev` CUDA devices are used.
    The order in `dev_list` defines the user-order of processors within the communicator.

    Parameters
    ----------
    dev_list : list[int] or None
        A list of CUDA device IDs to use for the communicators. If None,
        the first `ndev` devices are used.

    Returns
    -------
    ncclComm_t
        The first communicator in the array of initialized NCCL communicators.
    """
    comms = (ncclComm_t * len(dev_list))()  # type: ignore
    assert _libnccl
    status = _libnccl.ncclCommInitAll(comms, 0 if dev_list is None else len(dev_list), dev_list)
    ncclCheckStatus(status)
    comm = comms[0]
    return comm


# ncclResult_t  ncclCommDestroy(ncclComm_t comm);
_libnccl.ncclCommDestroy.restype = int
_libnccl.ncclCommDestroy.argtypes = [ncclComm_t]


def ncclCommDestroy(comm: ctypes._Pointer[NcclComm]) -> None:
    """Frees resources associated with a communicator object.

    This function waits for any operations that might still be running on the
    device associated with the communicator to complete before freeing resources.

    Parameters
    ----------
    comm : ncclComm_t
        The NCCL communicator to destroy.
    """
    assert _libnccl
    status = _libnccl.ncclCommDestroy(comm)
    ncclCheckStatus(status)


# ncclResult_t  ncclCommAbort(ncclComm_t comm);
_libnccl.ncclCommAbort.restype = int
_libnccl.ncclCommAbort.argtypes = [ctypes.c_void_p]


def ncclCommAbort(comm: ctypes._Pointer[NcclComm]) -> None:
    """Aborts all operations on a communicator and frees its resources.

    This function is typically used to clean up a communicator in case of an error.
    It frees resources associated with the communicator object and waits for any
    operations that might still be running on the device to complete.

    Parameters
    ----------
    comm : ncclComm_t
        The NCCL communicator to abort.
    """
    assert _libnccl
    status = _libnccl.ncclCommAbort(comm)
    ncclCheckStatus(status)


# ncclResult_t  ncclCommGetAsyncError(ncclComm_t comm, ncclResult_t *async_error);
_libnccl.ncclCommGetAsyncError.restype = int
_libnccl.ncclCommGetAsyncError.argtypes = [ctypes.c_void_p, ctypes.c_void_p]


def ncclCommGetAsyncError(comm: ctypes._Pointer[NcclComm]) -> int:
    """Checks if the communicator has encountered any asynchronous errors.

    Parameters
    ----------
    comm : ncclComm_t
        The NCCL communicator to check.

    Returns
    -------
    int
        The NCCL status code of the asynchronous error, or 0 if no error occurred.
    """
    async_error = ctypes.c_int()
    assert _libnccl
    status = _libnccl.ncclCommGetAsyncError(comm, ctypes.byref(async_error))
    ncclCheckStatus(status)
    return async_error.value


# ncclResult_t  ncclCommCount(const ncclComm_t comm, int* count);
_libnccl.ncclCommCount.restype = int
_libnccl.ncclCommCount.argtypes = [ctypes.c_void_p, ctypes.c_void_p]


def ncclCommCount(comm: ctypes._Pointer[NcclComm]) -> int:
    """Gets the number of ranks in the communicator clique.

    Parameters
    ----------
    comm : ncclComm_t
        The NCCL communicator.

    Returns
    -------
    int
        The number of ranks in the communicator.
    """

    count = ctypes.c_int()
    assert _libnccl
    status = _libnccl.ncclCommCount(comm, ctypes.byref(count))
    ncclCheckStatus(status)
    return count.value


# ncclResult_t  ncclCommCuDevice(const ncclComm_t comm, int* device);
_libnccl.ncclCommCuDevice.restype = int
_libnccl.ncclCommCuDevice.argtypes = [ctypes.c_void_p, ctypes.c_void_p]


def ncclCommCuDevice(comm: ctypes._Pointer[NcclComm]) -> int:
    """Returns the CUDA device number associated with the communicator.

    Parameters
    ----------
    comm : ncclComm_t
        The NCCL communicator.

    Returns
    -------
    int
        The CUDA device ID.
    """

    device = ctypes.c_int()
    assert _libnccl
    status = _libnccl.ncclCommCuDevice(comm, ctypes.byref(device))
    ncclCheckStatus(status)
    return device.value


# ncclResult_t  ncclCommUserRank(const ncclComm_t comm, int* rank);
_libnccl.ncclCommUserRank.restype = int
_libnccl.ncclCommUserRank.argtypes = [ctypes.c_void_p, ctypes.c_void_p]


def ncclCommUserRank(comm: ctypes._Pointer[NcclComm]) -> int:
    """Returns the user-ordered "rank" associated with the communicator.

    This is the rank that was passed during `ncclCommInitRank` or determined
    by the order in `dev_list` for `ncclCommInitAll`.

    Parameters
    ----------
    comm : ncclComm_t
        The NCCL communicator.

    Returns
    -------
    int
        The user-defined rank.
    """

    rank = ctypes.c_int()
    assert _libnccl
    status = _libnccl.ncclCommUserRank(comm, ctypes.byref(rank))
    ncclCheckStatus(status)
    return rank.value


# Reduction operation selector
class RedOp(Enum):
    """Enumeration for NCCL reduction operations."""

    Sum = 0
    Prod = 1
    Max = 2
    Min = 3
    NumOps = 4


# Data types
class DataType(Enum):
    """Enumeration for NCCL data types."""

    Int8 = Char = 0
    Uint8 = 1
    Int32 = Int = 2
    Uint32 = 3
    Int64 = 4
    Uint64 = 5
    Float16 = Half = 6
    Float32 = Float = 7
    Float64 = Double = 8
    NumTypes = 9


# Collective communication operations
#
# Collective communication operations must be called separately for each
# communicator in a communicator clique.
#
# They return when operations have been enqueued on the CUDA stream.
#
# Since they may perform inter-CPU synchronization, each call has to be done
# from a different thread or process, or need to use Group Semantics (see
# below).


# ncclResult_t  ncclReduce(const void* sendbuff, void* recvbuff, size_t count, ncclDataType_t datatype,
#     ncclRedOp_t op, int root, ncclComm_t comm, cudaStream_t stream);
_libnccl.ncclReduce.restype = int
_libnccl.ncclReduce.argtypes = [
    ctypes.c_void_p,
    ctypes.c_void_p,
    ctypes.c_ulong,
    ctypes.c_int,
    ctypes.c_int,
    ctypes.c_int,
    ncclComm_t,
    ctypes.c_void_p,
]


def ncclReduce(sendbuff: ctypes.c_void_p, recvbuff: ctypes.c_void_p, count: int, datatype: DataType, op: RedOp, root: int, comm: ctypes._Pointer[NcclComm], stream: ctypes.c_void_p) -> None:
    """Performs a reduction operation on data arrays.

    Reduces data arrays of length `count` in `sendbuff` into `recvbuff` using the specified `op` operation.
    `recvbuff` can be NULL on all calls except for the root device.
    The `root` is the rank where the data will reside after the operation is complete.
    An in-place operation will happen if `sendbuff` is the same as `recvbuff`.

    Parameters
    ----------
    sendbuff : ctypes.c_void_p
        Pointer to the send buffer.
    recvbuff : ctypes.c_void_p
        Pointer to the receive buffer.
    count : int
        The number of elements in the buffers.
    datatype : DataType
        The data type of the elements.
    op : RedOp
        The reduction operation to perform.
    root : int
        The rank of the root process.
    comm : ncclComm_t
        The NCCL communicator.
    stream : ctypes.c_void_p
        The CUDA stream to enqueue the operation on.

    Returns
    -------
    None
    """

    assert _libnccl
    status = _libnccl.ncclReduce(
        sendbuff, recvbuff, count, datatype.value, op.value, root, comm, stream
    )
    ncclCheckStatus(status)


# ncclResult_t  ncclBroadcast(const void* sendbuff, void* recvbuff, size_t count, ncclDataType_t datatype, int root,
#     ncclComm_t comm, cudaStream_t stream);
_libnccl.ncclBroadcast.restype = int
_libnccl.ncclBroadcast.argtypes = [
    ctypes.c_void_p,
    ctypes.c_void_p,
    ctypes.c_ulong,
    ctypes.c_int,
    ctypes.c_int,
    ncclComm_t,
    ctypes.c_void_p,
]


def ncclBroadcast(sendbuff: ctypes.c_void_p, recvbuff: ctypes.c_void_p, count: int, datatype: DataType, root: int, comm: ctypes._Pointer[NcclComm], stream: ctypes.c_void_p) -> None:
    """Broadcasts data from a root to all other devices.

    Copies `count` values from the `root` device to all other devices.
    The `root` is the rank where the data resides before the operation is started.
    An in-place operation will happen if `sendbuff` is the same as `recvbuff`.

    Parameters
    ----------
    sendbuff : ctypes.c_void_p
        Pointer to the send buffer (only used on the root device).
    recvbuff : ctypes.c_void_p
        Pointer to the receive buffer.
    count : int
        The number of elements to broadcast.
    datatype : DataType
        The data type of the elements.
    root : int
        The rank of the root process.
    comm : ncclComm_t
        The NCCL communicator.
    stream : ctypes.c_void_p
        The CUDA stream to enqueue the operation on.

    Returns
    -------
    None
    """

    assert _libnccl
    status = _libnccl.ncclBroadcast(sendbuff, recvbuff, count, datatype.value, root, comm, stream)
    ncclCheckStatus(status)


# ncclResult_t  ncclAllReduce(const void* sendbuff, void* recvbuff, size_t count,
#     ncclDataType_t datatype, ncclRedOp_t op, ncclComm_t comm, cudaStream_t stream);
_libnccl.ncclAllReduce.restype = int
_libnccl.ncclAllReduce.argtypes = [
    ctypes.c_void_p,
    ctypes.c_void_p,
    ctypes.c_ulong,
    ctypes.c_int,
    ctypes.c_int,
    ncclComm_t,
    ctypes.c_void_p,
]


def ncclAllReduce(sendbuff: ctypes.c_void_p, recvbuff: ctypes.c_void_p, count: int, datatype: DataType, op: RedOp, comm: ctypes._Pointer[NcclComm], stream: ctypes.c_void_p) -> None:
    """Performs an all-reduce operation.

    Reduces data arrays of length `count` in `sendbuff` using the specified `op` operation,
    and leaves identical copies of the result on each `recvbuff`.
    An in-place operation will happen if `sendbuff` is the same as `recvbuff`.

    Parameters
    ----------
    sendbuff : ctypes.c_void_p
        Pointer to the send buffer.
    recvbuff : ctypes.c_void_p
        Pointer to the receive buffer.
    count : int
        The number of elements in the buffers.
    datatype : DataType
        The data type of the elements.
    op : RedOp
        The reduction operation to perform.
    comm : ncclComm_t
        The NCCL communicator.
    stream : ctypes.c_void_p
        The CUDA stream to enqueue the operation on.

    Returns
    -------
    None
    """

    assert _libnccl
    status = _libnccl.ncclAllReduce(
        sendbuff, recvbuff, count, datatype.value, op.value, comm, stream
    )
    ncclCheckStatus(status)


# ncclResult_t  ncclReduceScatter(const void* sendbuff, void* recvbuff,
#     size_t recvcount, ncclDataType_t datatype, ncclRedOp_t op, ncclComm_t comm,
#     cudaStream_t stream);
_libnccl.ncclReduceScatter.restype = int
_libnccl.ncclReduceScatter.argtypes = [
    ctypes.c_void_p,
    ctypes.c_void_p,
    ctypes.c_ulong,
    ctypes.c_int,
    ctypes.c_int,
    ncclComm_t,
    ctypes.c_void_p,
]


def ncclReduceScatter(sendbuff: ctypes.c_void_p, recvbuff: ctypes.c_void_p, recvcount: int, datatype: DataType, op: RedOp, comm: ctypes._Pointer[NcclComm], stream: ctypes.c_void_p) -> None:
    """Performs a reduce-scatter operation.

    Reduces data in `sendbuff` using the `op` operation and scatters the reduced result
    over the devices. `recvbuff` on rank `i` will contain the `i`-th block of the result.
    Assumes `sendcount` is equal to `nranks` * `recvcount`, meaning `sendbuff`
    should have a size of at least `nranks` * `recvcount` elements.
    An in-place operation will happen if `recvbuff` is the same as `sendbuff` + `rank` * `recvcount`.

    Parameters
    ----------
    sendbuff : ctypes.c_void_p
        Pointer to the send buffer.
    recvbuff : ctypes.c_void_p
        Pointer to the receive buffer.
    recvcount : int
        The number of elements to receive on each rank.
    datatype : DataType
        The data type of the elements.
    op : RedOp
        The reduction operation to perform.
    comm : ncclComm_t
        The NCCL communicator.
    stream : ctypes.c_void_p
        The CUDA stream to enqueue the operation on.

    Returns
    -------
    None
    """

    assert _libnccl
    status = _libnccl.ncclReduceScatter(
        sendbuff, recvbuff, recvcount, datatype.value, op.value, comm, stream
    )
    ncclCheckStatus(status)


# ncclResult_t  ncclAllGather(const void* sendbuff, void* recvbuff, size_t sendcount,
#     ncclDataType_t datatype, ncclComm_t comm, cudaStream_t stream);
_libnccl.ncclAllGather.restype = int
_libnccl.ncclAllGather.argtypes = [
    ctypes.c_void_p,
    ctypes.c_void_p,
    ctypes.c_ulong,
    ctypes.c_int,
    ncclComm_t,
    ctypes.c_void_p,
]


def ncclAllGather(sendbuff: ctypes.c_void_p, recvbuff: ctypes.c_void_p, sendcount: int, datatype: DataType, comm: ctypes._Pointer[NcclComm], stream: ctypes.c_void_p) -> None:
    """Performs an all-gather operation.

    Each device gathers `sendcount` values from other GPUs into `recvbuff`.
    Data from rank `i` is received at offset `i` * `sendcount` in `recvbuff`.
    Assumes `recvcount` is equal to `nranks` * `sendcount`, meaning `recvbuff`
    should have a size of at least `nranks` * `sendcount` elements.
    An in-place operation will happen if `sendbuff` is the same as `recvbuff` + `rank` * `sendcount`.

    Parameters
    ----------
    sendbuff : ctypes.c_void_p
        Pointer to the send buffer.
    recvbuff : ctypes.c_void_p
        Pointer to the receive buffer.
    sendcount : int
        The number of elements to send from each rank.
    datatype : DataType
        The data type of the elements.
    comm : ncclComm_t
        The NCCL communicator.
    stream : ctypes.c_void_p
        The CUDA stream to enqueue the operation on.

    Returns
    -------
    None
    """

    assert _libnccl
    status = _libnccl.ncclAllGather(sendbuff, recvbuff, sendcount, datatype.value, comm, stream)
    ncclCheckStatus(status)


# ncclResult_t  ncclSend(const void* sendbuff, size_t count, ncclDataType_t datatype, int peer,
#     ncclComm_t comm, cudaStream_t stream);
_libnccl.ncclSend.restype = int
_libnccl.ncclSend.argtypes = [
    ctypes.c_void_p,
    ctypes.c_ulong,
    ctypes.c_int,
    ctypes.c_int,
    ncclComm_t,
    ctypes.c_void_p,
]


def ncclSend(sendbuff: ctypes.c_void_p, count: int, datatype: DataType, peer: int, comm: ctypes._Pointer[NcclComm], stream: ctypes.c_void_p) -> None:
    """Sends data from a buffer to a specific peer rank.

    The peer rank must call `ncclRecv` with the same `datatype` and `count` from this rank.
    This operation is blocking for the GPU. If multiple `ncclSend` and `ncclRecv` operations
    need to progress concurrently to complete, they must be fused within a `ncclGroupStart`/`ncclGroupEnd` section.

    Parameters
    ----------
    sendbuff : ctypes.c_void_p
        Pointer to the send buffer.
    count : int
        The number of elements to send.
    datatype : DataType
        The data type of the elements.
    peer : int
        The rank of the peer to send data to.
    comm : ncclComm_t
        The NCCL communicator.
    stream : ctypes.c_void_p
        The CUDA stream to enqueue the operation on.

    Returns
    -------
    None
    """

    assert _libnccl
    status = _libnccl.ncclSend(sendbuff, count, datatype.value, peer, comm, stream)
    ncclCheckStatus(status)


# ncclResult_t  ncclRecv(void* recvbuff, size_t count, ncclDataType_t datatype, int peer,
#    ncclComm_t comm, cudaStream_t stream);
_libnccl.ncclRecv.restype = int
_libnccl.ncclRecv.argtypes = [
    ctypes.c_void_p,
    ctypes.c_int,
    ctypes.c_int,
    ctypes.c_int,
    ncclComm_t,
    ctypes.c_void_p,
]


def ncclRecv(recvbuff: ctypes.c_void_p, count: int, datatype: DataType, peer: int, comm: ctypes._Pointer[NcclComm], stream: ctypes.c_void_p) -> None:
    """Receives data into a buffer from a specific peer rank.

    The peer rank must call `ncclSend` with the same `datatype` and `count` to this rank.
    This operation is blocking for the GPU. If multiple `ncclSend` and `ncclRecv` operations
    need to progress concurrently to complete, they must be fused within a `ncclGroupStart`/`ncclGroupEnd` section.

    Parameters
    ----------
    recvbuff : ctypes.c_void_p
        Pointer to the receive buffer.
    count : int
        The number of elements to receive.
    datatype : DataType
        The data type of the elements.
    peer : int
        The rank of the peer to receive data from.
    comm : ncclComm_t
        The NCCL communicator.
    stream : ctypes.c_void_p
        The CUDA stream to enqueue the operation on.

    Returns
    -------
    None
    """

    assert _libnccl
    status = _libnccl.ncclRecv(recvbuff, count, datatype.value, peer, comm, stream)
    ncclCheckStatus(status)


# ncclResult_t  ncclGroupStart();
_libnccl.ncclGroupStart.restype = int
_libnccl.ncclGroupStart.argtypes = []


def ncclGroupStart() -> None:
    """Starts a group of NCCL operations.

    All calls to NCCL functions until `ncclGroupEnd` will be fused into a single
    NCCL operation. Nothing will be started on the CUDA stream until `ncclGroupEnd` is called.

    Returns
    -------
    None
    """

    assert _libnccl
    status = _libnccl.ncclGroupStart()
    ncclCheckStatus(status)


# ncclResult_t  ncclGroupEnd();
_libnccl.ncclGroupEnd.restype = int
_libnccl.ncclGroupEnd.argtypes = []


def ncclGroupEnd() -> None:
    """Ends a group of NCCL operations and starts the fused operation.

    Starts a fused NCCL operation consisting of all calls made since `ncclGroupStart`.
    Operations on the CUDA stream that depend on the NCCL operations need to be called
    after `ncclGroupEnd`.

    Returns
    -------
    None
    """

    assert _libnccl
    status = _libnccl.ncclGroupEnd()
    ncclCheckStatus(status)
