"""
Tracer events
"""

#
#  This file is part of Python Distributed Training of Neural Networks (PyDTNN)
#
#  Copyright (C) 2021-22 Universitat Jaume I
#
#  PyDTNN is free software: you can redistribute it and/or modify it under the
#  terms of the GNU General Public License as published by the Free Software
#  Foundation, either version 3 of the License, or (at your option) any later
#  version.
#
#  This program is distributed in the hope that it will be useful, but WITHOUT
#  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
#  or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
#  License for more details.
#
#  You should have received a copy of the GNU General Public License along
#  with this program.  If not, see <https://www.gnu.org/licenses/>.
#

# ---
PYDTNN_MDL_EVENT = 60000001
PYDTNN_MDL_EVENTS = 5
(PYDTNN_MDL_FORWARD,
 PYDTNN_MDL_BACKWARD,
 PYDTNN_MDL_ALLREDUCE_DW,
 PYDTNN_MDL_WAIT_DW,
 PYDTNN_MDL_UPDATE_DW) = range(1, PYDTNN_MDL_EVENTS + 1)
# ---
PYDTNN_OPS_EVENT = 60000002
PYDTNN_OPS_EVENTS: int = 37
(PYDTNN_OPS_ALLREDUCE_DW,
 PYDTNN_OPS_BACKWARD_CONVGEMM,
 PYDTNN_OPS_BACKWARD_CUBLAS_MATMUL_DW,
 PYDTNN_OPS_BACKWARD_CUBLAS_MATMUL_DX,
 PYDTNN_OPS_BACKWARD_CUBLAS_MATVEC_DB,
 PYDTNN_OPS_BACKWARD_CUDNN_DB,
 PYDTNN_OPS_BACKWARD_CUDNN_DW,
 PYDTNN_OPS_BACKWARD_CUDNN_DX,
 PYDTNN_OPS_BACKWARD_DECONV_GEMM,
 PYDTNN_OPS_BACKWARD_ELTW_SUM,
 PYDTNN_OPS_BACKWARD_IM2COL,
 PYDTNN_OPS_BACKWARD_RESHAPE_DW,
 PYDTNN_OPS_BACKWARD_RESHAPE_DX,
 PYDTNN_OPS_BACKWARD_SPLIT,
 PYDTNN_OPS_BACKWARD_SUM_BIASES,
 PYDTNN_OPS_BACKWARD_TRANSPOSE_DY,
 PYDTNN_OPS_BACKWARD_TRANSPOSE_W,
 PYDTNN_OPS_COMP_DW_MATMUL,
 PYDTNN_OPS_COMP_DX_COL2IM,
 PYDTNN_OPS_COMP_DX_MATMUL,
 PYDTNN_OPS_FORWARD_DEPTHWISE_CONV,
 PYDTNN_OPS_FORWARD_POINTWISE_CONV,
 PYDTNN_OPS_FORWARD_CONCAT,
 PYDTNN_OPS_FORWARD_CONVGEMM,
 PYDTNN_OPS_FORWARD_CONVWINOGRAD,
 PYDTNN_OPS_FORWARD_CONVDIRECT,
 PYDTNN_OPS_FORWARD_CUBLAS_MATMUL,
 PYDTNN_OPS_FORWARD_CUDNN,
 PYDTNN_OPS_FORWARD_CUDNN_SUM_BIASES,
 PYDTNN_OPS_FORWARD_ELTW_SUM,
 PYDTNN_OPS_FORWARD_IM2COL,
 PYDTNN_OPS_FORWARD_MATMUL,
 PYDTNN_OPS_FORWARD_REPLICATE,
 PYDTNN_OPS_FORWARD_RESHAPE_W,
 PYDTNN_OPS_FORWARD_RESHAPE_Y,
 PYDTNN_OPS_FORWARD_SUM_BIASES,
 PYDTNN_OPS_FORWARD_TRANSPOSE_Y) = range(1, PYDTNN_OPS_EVENTS + 1)
