# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from pydtnn.comms.grpc import mpi_pb2 as pydtnn_dot_comms_dot_grpc_dot_mpi__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in pydtnn/comms/grpc/mpi_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MPIStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.send = channel.unary_unary(
                '/MPI/send',
                request_serializer=pydtnn_dot_comms_dot_grpc_dot_mpi__pb2.SendRequest.SerializeToString,
                response_deserializer=pydtnn_dot_comms_dot_grpc_dot_mpi__pb2.SendResponse.FromString,
                _registered_method=True)
        self.recv = channel.unary_stream(
                '/MPI/recv',
                request_serializer=pydtnn_dot_comms_dot_grpc_dot_mpi__pb2.RecvRequest.SerializeToString,
                response_deserializer=pydtnn_dot_comms_dot_grpc_dot_mpi__pb2.RecvResponse.FromString,
                _registered_method=True)


class MPIServicer(object):
    """Missing associated documentation comment in .proto file."""

    def send(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def recv(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MPIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'send': grpc.unary_unary_rpc_method_handler(
                    servicer.send,
                    request_deserializer=pydtnn_dot_comms_dot_grpc_dot_mpi__pb2.SendRequest.FromString,
                    response_serializer=pydtnn_dot_comms_dot_grpc_dot_mpi__pb2.SendResponse.SerializeToString,
            ),
            'recv': grpc.unary_stream_rpc_method_handler(
                    servicer.recv,
                    request_deserializer=pydtnn_dot_comms_dot_grpc_dot_mpi__pb2.RecvRequest.FromString,
                    response_serializer=pydtnn_dot_comms_dot_grpc_dot_mpi__pb2.RecvResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MPI', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('MPI', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MPI(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def send(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MPI/send',
            pydtnn_dot_comms_dot_grpc_dot_mpi__pb2.SendRequest.SerializeToString,
            pydtnn_dot_comms_dot_grpc_dot_mpi__pb2.SendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def recv(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/MPI/recv',
            pydtnn_dot_comms_dot_grpc_dot_mpi__pb2.RecvRequest.SerializeToString,
            pydtnn_dot_comms_dot_grpc_dot_mpi__pb2.RecvResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
