# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pydtnn/comms/grpc/mpi.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'pydtnn/comms/grpc/mpi.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bpydtnn/comms/grpc/mpi.proto\")\n\x0bSendRequest\x12\x0c\n\x04rank\x18\x01 \x01(\x0f\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"\x0e\n\x0cSendResponse\":\n\x0bRecvRequest\x12\x0c\n\x04rank\x18\x01 \x01(\x0f\x12\x0c\n\x04size\x18\x02 \x01(\x0f\x12\x0f\n\x02op\x18\x03 \x01(\x0e\x32\x03.Op\"\x1c\n\x0cRecvResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c*-\n\x02Op\x12\t\n\x05\x42\x43\x41ST\x10\x00\x12\r\n\tALLGATHER\x10\x02\x12\r\n\tALLREDUCE\x10\x03\x32U\n\x03MPI\x12%\n\x04send\x12\x0c.SendRequest\x1a\r.SendResponse\"\x00\x12\'\n\x04recv\x12\x0c.RecvRequest\x1a\r.RecvResponse\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pydtnn.comms.grpc.mpi_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OP']._serialized_start=180
  _globals['_OP']._serialized_end=225
  _globals['_SENDREQUEST']._serialized_start=31
  _globals['_SENDREQUEST']._serialized_end=72
  _globals['_SENDRESPONSE']._serialized_start=74
  _globals['_SENDRESPONSE']._serialized_end=88
  _globals['_RECVREQUEST']._serialized_start=90
  _globals['_RECVREQUEST']._serialized_end=148
  _globals['_RECVRESPONSE']._serialized_start=150
  _globals['_RECVRESPONSE']._serialized_end=178
  _globals['_MPI']._serialized_start=227
  _globals['_MPI']._serialized_end=312
# @@protoc_insertion_point(module_scope)
