"""Module for managing the state of PyDTNN models, including serialization and initialization."""

from __future__ import annotations

import logging
from typing import Any

import numpy as np
import yaml

from pydtnn.model.init import Init
from pydtnn.utils.constants import Array, Parameters

__all__ = ("State",)

logger = logging.getLogger(__name__)


class State[T: Array](Init[T]):  # noqa: D101 (generics not detected)
    """
    Handles the state management, serialization, and deserialization of model parameters.

    This class provides methods to export the current model's state (weights, biases, etc.)
    to a dictionary or file, and to import state from such sources. It also integrates
    with the initialization process to load pre-trained states.
    """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        """Initialize the layers model instance."""
        super().__init__(*args, **kwargs)
        self.history = []

    def _model_init(self) -> None:
        """
        Initializes the model and loads state from a file if specified.

        This method is called during the model's initialization phase. If a
        `model_state_file` is configured, it attempts to load the model's
        state from that file.
        """
        super()._model_init()

        # Load weights and bias
        if self.model_state_file:
            self.load_model_state(self.model_state_file)

        # Store current configuration
        props = {}

        if groups := self.config.get("groups"):
            config = {}
            for group in groups:
                if not group.title:
                    continue
                config[group.title] = {
                    action.dest: str(self.config[action.dest])
                    for action in group._group_actions
                    if action.dest in self.config
                }
        else:
            config = self.config
        if config:
            props["config"] = config

        if self.loss_func:
            props["loss"] = self.loss_func._show_props()

        if self.metrics_funcs:
            props["metrics"] = [metric._show_props() for metric in self.metrics_funcs]

        if self.optimizer:
            props["optimizer"] = self.optimizer._show_props()

        if self.schedulers:
            props["schedulers"] = [scheduler._show_props() for scheduler in self.schedulers]

        if self.dataset:
            props["dataset"] = self.dataset._show_props()

        if self.layers:
            props["layers"] = [layer._show_props() for layer in self.get_all_layers()]

        self.history_append(props)

    def export(self) -> dict[str, Any]:
        """
        Exports the current model state to a dictionary.

        The exported dictionary contains the model's name (if set) and a list
        of dictionaries, where each inner dictionary represents the state of a layer.

        Returns:
            A dictionary containing the model name and serialized layer data.
        """
        data = {}

        if not self.model_name:
            data[Parameters.MODEL_NAME] = self.model_name

        data[Parameters.LAYERS] = [layer.export() for layer in self.layers]

        return data

    def import_(self, data: dict[str, Any] | State) -> None:
        """
        Imports model state from a dictionary or another State instance.

        This method populates the model's layers with parameters loaded from the
        provided data. It checks for model name consistency and warns if they differ.
        If the model has not been initialized with layers yet, it attempts to
        initialize them based on the imported model name.

        Args:
            data: The state data to import. This can be a dictionary containing
                  model parameters or another `State` instance from which to export data.
        """
        if isinstance(data, State):
            data = data.export()

        model_name = str(data.get(Parameters.MODEL_NAME, ""))
        if model_name != str(self.model_name):
            logger.warning(
                f"Importing from different models! (self: {self.model_name}, got: {model_name})"
            )

        if model_name and not self._model_inited and not self.layers:
            self._layers_init(model_name)

        for layer, data in zip(self.layers, data[Parameters.LAYERS]):
            layer.import_(data)  # pyright: ignore[reportArgumentType]

    def load_model_state(self, filename: str) -> None:
        """
        Loads model weights and biases from a file.

        This method uses `numpy.load` to read state data from a specified file
        and then imports this data into the model using the `import_` method.

        Args:
            filename: Path to the file with the weights and biases to load.
                      This file is typically generated by `save_model_state`.
        """
        with np.load(filename, allow_pickle=True) as data:
            self.import_(data)

    def save_model_state(self, filename: str, compress: bool = True) -> None:
        """
        Saves the current model weights and biases to a file.

        The model's state is exported to a dictionary and then saved to the
        specified file using `numpy.savez` or `numpy.savez_compressed`.

        Args:
            filename: Path to the file where the weights and biases will be stored.
            compress: Whether to use compressed storage (`numpy.savez_compressed`).
                      Defaults to `True`.
        """
        save = np.savez_compressed if compress else np.savez
        save(filename, **self.export())

    def history_append(self, event: dict) -> str:
        """Append history event"""
        if history_file := self.history_file:
            mode = "a" if self.history else "w"
            from pydtnn.utils.serial import ReprYaml

            with open(history_file, mode) as f:
                if self.history:
                    f.write("---\n")
                yaml.dump(event, f, ReprYaml, allow_unicode=True, sort_keys=False)
        self.history.append(event)
