#!/bin/bash

export OMP_NUM_THREADS=8
export MKL_NUM_THREADS=8
#export GOMP_CPU_AFFINITY="2 4 6 8 10 12 14 16"
export PYTHONOPTIMIZE=2
#export OMP_DISPLAY_ENV=True
#export OMP_DISPLAY_AFFINITY=True
export PYTHONUNBUFFERED="True"
#mpirun -np 2 \
pydtnn-benchmark \
  --model=vgg3dobn \
  --dataset=cifar10 \
  --dataset-path=datasets/cifar10 \
  --normalize=True \
  --normalize-offset=-0.472 \
  --normalize-scale=1 \
  --test-as-validation=True \
  --augment-flip=False \
  --augment-crop=False \
  --batch-size=64 \
  --validation-split=0.2 \
  --steps-per-epoch=0 \
  --num-epochs=10 \
  --evaluate=False \
  --optimizer=sgd \
  --optimizer-nesterov=False \
  --learning-rate=0.01 \
  --optimizer-decay=1e-4 \
  --optimizer-momentum=0.9 \
  --loss-func=categorical_cross_entropy \
  --metrics=categorical_accuracy \
  --schedulers=warm_up,reduce_lr_on_plateau \
  --warm-up-epochs=5 \
  --early-stopping-metric=val_categorical_cross_entropy \
  --early-stopping-patience=20 \
  --reduce-lr-on-plateau-metric=val_categorical_cross_entropy \
  --reduce-lr-on-plateau-factor=0.1 \
  --reduce-lr-on-plateau-patience=15 \
  --reduce-lr-on-plateau-min-lr=0.0001 \
  --reduce-lr-every-nepochs-factor=0.5 \
  --reduce-lr-every-nepochs-nepochs=50 \
  --reduce-lr-every-nepochs-min-lr=0.001 \
  --stop-at-loss-metric=val_categorical_accuracy \
  --stop-at-loss-threshold=70.0 \
  --parallel=sequential \
  --use-blocking-mpi=True \
  --tracing=False \
  --profile=False \
  --backend=cpu \
  --enable-cudnn=False \
  --enable-cudnn-auto-conv-alg=False \
  --enable-gpudirect=False \
  --history-file="results/result_vgg3dobn.history" \
  --dtype=float32
