"""
Memory cache utility for PyDTNN.

Provides a dictionary-like structure with a factory function for missing keys
and global cache control mechanisms.
"""
import logging

__all__ = ("MemoryCache",)

logger = logging.getLogger(__name__)


class MemoryCache(dict):
    """
    Dictionary derived class that can use the provided factory function to
    obtain a default value for a missing key. It differs from defaultdict in:

    * The provided factory function receives key as a parameter (which allows
      the generated value to depend on the given key).

    * If disable() is called, the instances of this class will clear their
      already stored values and will not store the next ones.

    """

    _preserve_values = True

    def __init__(self, default_factory=None, **kwargs):
        """
        Initialize the MemoryCache.

        Args:
            default_factory: Callable to generate values for missing keys.
            **kwargs: Initial dictionary values.
        """
        super().__init__(self, **kwargs)
        self.default_factory = default_factory

    def __missing__(self, key):
        """
        Handle missing keys by invoking the default_factory.

        Args:
            key: The key to retrieve.

        Returns:
            The value generated by the factory.

        Raises:
            KeyError: If no default_factory is provided.
        """
        if self.default_factory is None:
            raise KeyError(key)
        else:
            ret = self.default_factory(key)
            if self._preserve_values:
                self[key] = ret
            return ret

    @classmethod
    def disable(cls, update: bool = False):
        """
        Disable caching and optionally clear all existing instances.

        Args:
            update: If True, clears all existing MemoryCache instances.
        """
        cls._preserve_values = False
        if not update:
            return
        import gc

        for obj in gc.get_objects():
            if isinstance(obj, cls):
                obj.clear()

    @classmethod
    def enable(cls):
        """Enable caching for all MemoryCache instances."""
        cls._preserve_values = True