version: 1
formatters:
  brief:
    format: '%(message)s'
  precise:
    format: '[%(asctime)s] [%(name)s] [%(levelname)s]: %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: precise
    stream: ext://sys.stderr
  file:
    class: logging.FileHandler
    formatter: precise
    filename: logging.log
    mode: w
loggers:
  pydtnn:
    level: INFO
    handlers: [console, file]
